version: '3'

services:
  rust:
    build:
      context: .
      args:
        - UNAME=$UNAME
        - UID=$UID
        - GID=$GID
    env_file: .env
    user: $UNAME
    ports:
      - 8080:8080
    volumes:
      - .:/app
    tty: true